### ISSUE TITLE
Karpetak ez ditu ondo egiten

### ISSUE THREAD

**Issue by poxtius** [ionhs/ROS-Gazebo-jetbot#1]
gazebo_ws karpetan sartu beharreko fitxategiak ez dizkit sartzen eta gainera root-ek bakarrik dauka baimena eta tknika usuarioarenk izan behako litzateke.

**Comment by ionhs** [comment]
Arrazoi, arazorenbat dago gazebo_ws karpetarekin. Hutsa sortzen du eta jabetza root-arena da. Probak egingo ditut

**Comment by bodiroga** [comment]
@poxtius @ionhs @LaraBurgoa Hemen aurkitu dezakezue zuen galderaren erantzuna:

https://linuxhandbook.com/tmp-directory/#:~:text=What%20is%20the%20%2Ftmp%20directory,tmp%20directory%20after%20each%20reboot.

"As the name suggests, the tmp (temporary) directory under root is used to store the data used by the system and user applications to store the data that are needed for a short period of time. Most Linux distributions are preconfigured to empty the tmp directory after each reboot."

Dockerfile-eko "/tmp/curso_ros" karpeta "opt/curso_ros"ekin ordezkatu.

PD: Faktura hurrengo astean pasako diot Larari 😉

**Comment by bodiroga** [comment]
@poxtius @ionhs @LaraBurgoa Azkarregi idatzi nuen atzo, ez da hori arazoa, hau baizik:

https://forums.docker.com/t/docker-bind-mount-is-deleting-containers-files/135541

Eta oraindik ez dakit nola konpondu daitekeen 😢

**Comment by bodiroga** [comment]
@poxtius @ionhs @LaraBurgoa Ready to review: https://github.com/ionhs/ROS-Gazebo-jetbot/pull/2

PD: Ordu kopuruagatik faktura nahiko altua izango da 😉

**Comment by ionhs** [comment]
@bodiroga -k issue-a konpondu du. Arazoa gure ekipoko eta kontenedoreko karpeta mapeatzean zegoen. Berez gure ekipoko karpeta kontenedorean mapeatzen da baina gure ekipoko karpeta hutsa badago kontainerreko ezabatzen du. Beraz hau egiteko beste enfoke bat eman zaio.
Kontenedoreko karpetan eduki nahi dugun edukina beste karpeta batean gorde da. Kontainerraren eta ekipoaren karpetak mapeatu ondoren hutsa badago edukina beste karpeta horretatik kopiatu egiten du. hutsa ez badago ez da kopiatuko. Horrela script honek behin bakarrik ejekutatzen da.
